apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: greenergy-deployment
  labels:
    app: greenergy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenergy
  template:
    metadata:
      labels:
        app: greenergy
    spec:
      containers:
      - name:  greenergy
        image: sorbra/greenergy.data.energinet:dev
        imagePullPolicy: Always
        volumeMounts: 
        - name: "appsettings"
          mountPath: "/app/greenergy/appsettings.json"
          subPath: "appsettings.json"
      volumes:
      - name: "appsettings"
        configMap: 
          name: "greenergy.syncdata.energinetdk-kubemongo"
